---
version: '3.5'
services:

  postgresql:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dataverse
      - POSTGRES_PASSWORD=changeme

  solr:
    image: ucsdets/dataverse-solr
    expose:
      - 8983

  dataverse:
    build:
      context: .
      dockerfile: ./docker/dataverse-k8s/glassfish-dev/Dockerfile
    image: iqss/dataverse-k8s:dev
    depends_on:
      - postgresql
      - solr
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./personas/docker-compose/secrets
        target: /secrets
        read_only: true
