---
apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
    - image: iqss/dataverse-k8s
      context: .
      docker:
        dockerfile: docker/dataverse-k8s/glassfish-dev/Dockerfile
    - image: ucsdets/dataverse-solr
      context: docker/solr-k8s
  local: {}
deploy:
  kustomize:
    path: personas/dev

profiles:
  - name: init
    deploy:
      kustomize:
        path: personas/demo
  - name: payara
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: docker/dataverse-k8s/payara-dev/Dockerfile
