apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - solr
  - dataverse

images:
  - name: iqss/dataverse-k8s
    newTag: "4.20"
  - name: ucsdets/dataverse-solr
    newTag: "4.20"
