---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/IQSS/dataverse-kubernetes/k8s/solr?ref=v4.20

images:
  - name: ucsdets/dataverse-solr
    newTag: "4.20"

patchesStrategicMerge:
  - patch-pvc.yaml
  - patch-pull-always.yaml
