---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-postgresql
  labels:
    app.kubernetes.io/name: dataverse-postgresql
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  username: dataverse
  password: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-doi
  labels:
    app.kubernetes.io/name: dataverse-doi
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  username: test.doi
  password: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-api
  labels:
    app.kubernetes.io/name: dataverse-api
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  key: supersecret

###   ###   ###   ###   ###   ###   ###   ###   ###
# Example Secret for builtin user dataverseAdmin.
# See https://dataverse-k8s.readthedocs.io/en/latest/day1/secrets.html#example-admin-account-password
###   ###   ###   ###   ###   ###   ###   ###   ###
---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-admin
  labels:
    app.kubernetes.io/name: dataverse-admin
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  password: admin1


###   ###   ###   ###   ###   ###   ###   ###   ###
# Example Secret for external authentication providers
# See https://dataverse-k8s.readthedocs.io/en/latest/day3/auth.html#add-secrets-for-credentials
###   ###   ###   ###   ###   ###   ###   ###   ###
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: dataverse-providers
#  labels:
#    app.kubernetes.io/name: dataverse-providers
#    app.kubernetes.io/version: "1.0"
#    app.kubernetes.io/component: secret
#    app.kubernetes.io/part-of: dataverse
#    app.kubernetes.io/managed-by: kubectl
#type: Opaque
#stringData:
#  github_clientid: xxxx
#  github_clientsecret: xxxx
#  orcid_clientid: yyyy
#  orcid_clientsecret: yyyy
